
services:
  unstuck-ai:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "5900:5900"
      - "6080:6080"
    volumes:
      - ./mcp_server:/home/unstuck/mcp_server
      - ./.env:/home/unstuck/mcp_server/.env
    environment:
      - NOSTR_PRIVATE_KEY=${NOSTR_PRIVATE_KEY}
      - NWC_KEY=${NWC_KEY}
      - RELAY_URLS=${RELAY_URLS}
      - PORT=8000
      - HOST=0.0.0.0
      - DIGITAL_OCEAN_SPACES_ACCESS_KEY=${DIGITAL_OCEAN_SPACES_ACCESS_KEY}
      - DIGITAL_OCEAN_SPACES_SECRET_KEY=${DIGITAL_OCEAN_SPACES_SECRET_KEY}
      - DIGITAL_OCEAN_SPACE_NAME=${DIGITAL_OCEAN_SPACE_NAME}
      - DIGITAL_OCEAN_REGION_NAME=${DIGITAL_OCEAN_REGION_NAME}
