# /agents/goose-docker/docker-compose.yml

services:
  goose-agent:
    build:
      context: ../..
      dockerfile: agents/goose-docker/Dockerfile
    container_name: goose-docker-agent
    
    ports:
      - "5901:5901"   # VNC
      - "6080:6080"   # noVNC (web VNC)
      - "8888:8888"   # External Goose API
    
    volumes:
      - ./workspace:/home/goose/workspace
    
    environment:
      - DISPLAY=:1
      - ":1=true"
      - VNC_RESOLUTION=1920x1080
      - VNC_DEPTH=24
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      # Goose-specific environment variables
      - GOOSE_DISABLE_KEYRING=1
      - GOOSE_DEBUG=1
      # Experimental sandbox settings
      - GOOSE_SANDBOX_MODE=true
      - GOOSE_ALLOW_SUDO=true
      - DISABLE_SAFETY_CHECKS=true
      - GOOSE_DISABLE_COMMAND_FILTERING=true
      # Unstuck MCP server environment variables
      - NOSTR_PRIVATE_KEY=${NOSTR_PRIVATE_KEY}
      - NWC_KEY=${NWC_KEY}
      - RELAY_URLS=${RELAY_URLS}
      - DIGITAL_OCEAN_SPACES_ACCESS_KEY=${DIGITAL_OCEAN_SPACES_ACCESS_KEY}
      - DIGITAL_OCEAN_SPACES_SECRET_KEY=${DIGITAL_OCEAN_SPACES_SECRET_KEY}
      - DIGITAL_OCEAN_SPACE_NAME=${DIGITAL_OCEAN_SPACE_NAME}
    
    stdin_open: true
    tty: true
    
    restart: unless-stopped